services:
  my-cassandra: # Renamed the service to 'my-cassandra'
    image: cassandra:latest
    container_name: aziz-ai-cassandra # Updated the container name as requested
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=Rack1
    volumes:
      - my-cassandra-data:/var/lib/cassandra # Updated the volume name
      - ./cdc:/var/lib/cassandra/cdc_raw
    networks:
      - shared-net
    restart: always
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  app:
    container_name: IA-agent
    build: .
    depends_on:
      my-cassandra: # Updated dependency to the new service name
        condition: service_healthy
    ports:
      - "8001:8001"

    labels:
      - "maintainer=aziz" # Added a label with the name "aziz"

    environment:
      ENVIRONMENT: dev
      CASSANDRA_HOST: my-cassandra # Updated the CASSANDRA_HOST to the new service name
      CASSANDRA_PORT: 9042
      KEYSPACE: store

    networks:
      - shared-net
    restart: unless-stopped

volumes:
  my-cassandra-data: # Updated the volume name

networks:
  shared-net:
    driver: bridge
